spring.application.name=employee-service

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Circuit Breaker Configuration

resilience4j.circuitbreaker.instances.departmentService.registerHealthIndicator=true

resilience4j.circuitbreaker.instances.departmentService.slidingWindowSize=5

resilience4j.circuitbreaker.instances.departmentService.minimumNumberOfCalls=5

resilience4j.circuitbreaker.instances.departmentService.failureRateThreshold=50

resilience4j.circuitbreaker.instances.departmentService.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.departmentService.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.departmentService.automaticTransitionFromOpenToHalfOpenEnabled=true

management.endpoints.web.exposure.include=*

# Retry Configuration
resilience4j.retry.instances.departmentServiceRetry.maxAttempts=4
resilience4j.retry.instances.departmentServiceRetry.waitDuration=1s

resilience4j.retry.instances.departmentServiceRetry.enableExponentialBackoff=true
resilience4j.retry.instances.departmentServiceRetry.exponentialBackoffMultiplier=2

resilience4j.retry.instances.departmentServiceRetry.ignoreExceptions=java.lang.IllegalArgumentException


# Aspect Order
resilience4j.retry.retryAspectOrder=1
resilience4j.circuitbreaker.circuitBreakerAspectOrder=2
